name: End-to-end tests

on:
    pull_request:
        branches: [master]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  build: yarn run build
                  browser: chrome
                  start: yarn run serve
                  record: true
                  wait-on: 'http://localhost:8081'
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
