name: Publish Package to npmjs
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@tybalt'

            - name: Install dependencies
              run: yarn

            - name: Build monorepo
              run: yarn build

            - name: Configure yarn client
              run: yarn config set npmAuthToken "$NPM_TOKEN"
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish packages
              run: yarn workspaces foreach --all --no-private npm publish

            - name: Post to Discord
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              uses: Ilshidur/action-discord@0.3.2
              with:
                  args: 'A new version of Tybalt has been published.'
